### ISSUE TITLE
Allow for server-free usage; ie make it work on static hosting providers

### ISSUE THREAD

**Issue by Bernd-L** [Bernd-L/exDateMan#143]
# Objective

The goal of this issue is to make this application work on GitHub pages.

My other project (which is currently also the one I'm spending most of my time on) called DoubleNote (see <https://github.com/Bernd-L/DoubleNote>) is hosted at <https://bernd-l.github.io/DoubleNote/>.

This project would then be hosted at <https://bernd-l.github.io/ExDateMan/>.

However, the application (unlike DoubleNote) currently depends on a server (at least initially).

# Tasks

- [ ] Allow for offline-only mode
- [ ] Make the login optional
- [ ] Allow for offline inventory creation
- [ ] Allow for JSON imports & exports
