### ISSUE TITLE
Deploy on GH pages

### ISSUE THREAD

**Issue by Bernd-L** [Bernd-L/exDateMan#144]
# Objective

The application needs to be compatible with static serving; see #143 

Host this project on GH pages:  
This project would then be hosted at <https://bernd-l.github.io/ExDateMan/>.

# Tasks

- [ ] Set up a `gh-pages` branch
- [ ] Make the branch the default option for GitHub Pages in the repo settings
- [ ] Use this GitHub Action to automate the build & deploy: <https://github.com/marketplace/actions/angular-deploy-gh-pages-actions>
- [ ] Have it run at least once
- [ ] Checkout the branch locally
- [ ] Create a symlink for the 404 page (run `ln -s index.html 404.html`)
- [ ] Commit the symlink
- [ ] Push to `origin/gh-pages`
- [ ] Add a link to the README (<https://bernd-l.github.io/ExDateMan/>)
